[package]
name = "ic-papi-api"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
cycles-ledger-client = { workspace = true }
ic-ledger-types = { workspace = true }
hex = { workspace = true }
