#!/usr/bin/env bash
set -x

# Needs env vars:
POCKET_IC_SERVER_VERSION="${POCKET_IC_SERVER_VERSION:-5.0.0}"
POCKET_IC_SERVER_PATH="${POCKET_IC_SERVER_PATH:-./pocket-ic}"

if [[ $OSTYPE == "linux-gnu"* ]] || [[ $RUNNER_OS == "Linux" ]]; then
  PLATFORM=linux
elif [[ $OSTYPE == "darwin"* ]] || [[ $RUNNER_OS == "macOS" ]]; then
  PLATFORM=darwin
else
  echo "OS not supported: ${OSTYPE:-$RUNNER_OS}"
  exit 1
fi

if "$POCKET_IC_SERVER_PATH" --version 2>/dev/null | grep -wq "$POCKET_IC_SERVER_VERSION"; then
  echo "PocketIC server already exists at: $POCKET_IC_SERVER_PATH"
  echo "Skipping download."
else
  echo "Downloading PocketIC."
  curl -sSL https://github.com/dfinity/pocketic/releases/download/${POCKET_IC_SERVER_VERSION}/pocket-ic-x86_64-${PLATFORM}.gz -o ${POCKET_IC_SERVER_PATH}.gz
  gunzip ${POCKET_IC_SERVER_PATH}.gz
  chmod +x ${POCKET_IC_SERVER_PATH}
fi
