[package]
name = "ic-papi-guard"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = { workspace = true }
cycles-ledger-client = { workspace = true }
ic-cdk = "0.16.0"
ic-papi-api = { workspace = true }
serde_bytes = { workspace = true }
