[package]
name = "ic-papi-guard"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = { workspace = true }
ic-cdk = "0.17.1"
ic-cycles-ledger-client = { workspace = true }
ic-papi-api = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
