[package]
name = "cycles-ledger-client"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_bytes = { workspace = true }
candid = { workspace = true }
ic-cdk = { workspace = true }
